FROM ubuntu:24.10

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y \
    tzdata \
    nginx \
    php-fpm \
    php-cli \
    php-pdo \
    php-mysql \
    php-sqlite3 \
    php-xml \
    php-xmlwriter \
    php-libxml \
    php-dom \
    php-curl \
    php-tokenizer \
    php-json\
    php-mbstring  \
    curl \
    unzip \
    mysql-server \
    vim \
    && cp /usr/share/zoneinfo/Asia/Taipei /etc/localtime \
    && rm -rf /var/lib/apt/lists/* \
    && ln -s /usr/sbin/php-fpm8.3 /usr/local/sbin/php-fpm

# install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

WORKDIR /var/www/html
COPY . .

RUN composer update

RUN composer install

COPY docker/nginx/website.conf /etc/nginx/conf.d/website.conf
COPY docker/nginx/nginx.conf /etc/nginx/nginx.conf
COPY docker/php-fpm/www.conf /etc/php/8.3/fpm/pool.d/www.conf

RUN chmod 777 /var/www/html/storage -R

## mysql
RUN service mysql restart


ENTRYPOINT ["sh", "/var/www/html/docker/entrypoint.sh"]
